---
services:

  snapserver:
    build: ./snapserver
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
    volumes:
      - streamfile:/tmp
    env_file:
      - .env
    networks:
      snapcast_network:
        ipv4_address: ${SNAPSERVER_IP}

  radio:
    build: ./radio
    ports:
      - "6601:6600"
    volumes:
      - streamfile:/tmp
   
volumes:
  streamfile:
    name: streamfile

networks:
  snapcast_network:
    driver: macvlan
    driver_opts:
      parent: ${MACVLAN_PARENT_INTERFACE}
    ipam:
      config:
        - subnet: ${MACVLAN_SUBNET}
          ip_range: ${MACVLAN_IP}
          gateway: ${MACVLAN_GATEWAY}
