import RPi.GPIO as GPIO

# Define GPIO ports
SPOTIFY_LED = 17
RADIO_LED = 27
RADIO_BTN = 24
SRC_SEL_RADIO = 22
SRC_SEL_SPOTIFY = 23

GPIO.setmode(GPIO.BCM)
GPIO.setup(SPOTIFY_LED, GPIO.OUT)
GPIO.setup(RADIO_LED, GPIO.OUT)
GPIO.setup(RADIO_BTN, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(SRC_SEL_RADIO, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(SRC_SEL_SPOTIFY, GPIO.IN, pull_up_down=GPIO.PUD_UP)

